// Language mapping based on states
export const STATE_LANGUAGES: Record<string, string[]> = {
  'Tamil Nadu': ['Tamil', 'English'],
  'Bihar': ['Hindi', 'Urdu', 'English'],
  'Maharashtra': ['Marathi', 'Hindi', 'English'],
  'West Bengal': ['Bengali', 'Hindi', 'English'],
  'Karnataka': ['Kannada', 'English'],
  'Kerala': ['Malayalam', 'English'],
  'Andhra Pradesh': ['Telugu', 'English'],
  'Telangana': ['Telugu', 'Hindi', 'English'],
  'Gujarat': ['Gujarati', 'Hindi', 'English'],
  'Rajasthan': ['Hindi', 'English'],
  'Punjab': ['Punjabi', 'Hindi', 'English'],
  'Uttar Pradesh': ['Hindi', 'Urdu', 'English'],
  'Madhya Pradesh': ['Hindi', 'English'],
  'Odisha': ['Odia', 'English'],
  'Assam': ['Assamese', 'Bengali', 'English'],
  'Jharkhand': ['Hindi', 'English'],
  'Chhattisgarh': ['Hindi', 'English'],
  'Uttarakhand': ['Hindi', 'English'],
  'Haryana': ['Hindi', 'English'],
  'Himachal Pradesh': ['Hindi', 'English'],
  'Goa': ['Konkani', 'Marathi', 'English'],
  'Delhi': ['Hindi', 'Urdu', 'English'],
};

export type Language = 'English' | 'Hindi' | 'Tamil' | 'Telugu' | 'Marathi' | 'Bengali' | 'Kannada' | 'Malayalam' | 'Gujarati' | 'Punjabi' | 'Urdu' | 'Odia' | 'Assamese' | 'Konkani';

export const getLanguagesForState = (state: string): string[] => {
  return STATE_LANGUAGES[state] || ['English'];
};

// Translations for UI elements
export const translations: Record<Language, any> = {
  English: {
    yourEligibleSchemes: 'Your Eligible Schemes',
    found: 'Found',
    schemes: 'schemes',
    scheme: 'scheme',
    forYou: 'for you',
    logout: 'Logout',
    yourProfile: 'Your Profile',
    age: 'Age',
    years: 'years',
    gender: 'Gender',
    occupation: 'Occupation',
    state: 'State',
    income: 'Income',
    noSchemes: 'No schemes found matching your profile at this time.',
    checkBack: 'Please check back later or update your details.',
    youAreEligible: 'You are eligible',
    whyEligible: "Why You're Eligible",
    aboutScheme: 'About This Scheme',
    documentsNeeded: 'Documents Needed',
    howToApply: 'How to Apply',
    applyForScheme: 'Apply for this scheme',
    selectLanguage: 'Select Language',
    chatWithUs: 'Chat with us',
    askQuestion: 'Ask a question about schemes...',
    send: 'Send',
    chatbotWelcome: 'Hello! I can help you understand these government schemes. Ask me anything!',
  },
  Hindi: {
    yourEligibleSchemes: 'आपकी पात्र योजनाएं',
    found: 'मिली',
    schemes: 'योजनाएं',
    scheme: 'योजना',
    forYou: 'आपके लिए',
    logout: 'लॉग आउट',
    yourProfile: 'आपकी प्रोफ़ाइल',
    age: 'आयु',
    years: 'वर्ष',
    gender: 'लिंग',
    occupation: 'व्यवसाय',
    state: 'राज्य',
    income: 'आय',
    noSchemes: 'इस समय आपकी प्रोफ़ाइल से मेल खाने वाली कोई योजना नहीं मिली।',
    checkBack: 'कृपया बाद में फिर से जांचें या अपने विवरण अपडेट करें।',
    youAreEligible: 'आप पात्र हैं',
    whyEligible: 'आप क्यों पात्र हैं',
    aboutScheme: 'इस योजना के बारे में',
    documentsNeeded: 'आवश्यक दस्तावेज',
    howToApply: 'आवेदन कैसे करें',
    applyForScheme: 'इस योजना के लिए आवेदन करें',
    selectLanguage: 'भाषा चुनें',
    chatWithUs: 'हमसे बात करें',
    askQuestion: 'योजनाओं के बारे में प्रश्न पूछें...',
    send: 'भेजें',
    chatbotWelcome: 'नमस्ते! मैं आपको इन सरकारी योजनाओं को समझने में मदद कर सकता हूं। मुझसे कुछ भी पूछें!',
  },
  Tamil: {
    yourEligibleSchemes: 'உங்கள் தகுதியான திட்டங்கள்',
    found: 'கிடைத்தது',
    schemes: 'திட்டங்கள்',
    scheme: 'திட்டம்',
    forYou: 'உங்களுக்காக',
    logout: 'வெளியேறு',
    yourProfile: 'உங்கள் சுயவிவரம்',
    age: 'வயது',
    years: 'வருடங்கள்',
    gender: 'பாலினம்',
    occupation: 'தொழில்',
    state: 'மாநிலம்',
    income: 'வருமானம்',
    noSchemes: 'இந்த நேரத்தில் உங்கள் சுயவிவரத்துடன் பொருந்தும் திட்டங்கள் இல்லை.',
    checkBack: 'பிறகு மீண்டும் சரிபார்க்கவும் அல்லது உங்கள் விவரங்களைப் புதுப்பிக்கவும்.',
    youAreEligible: 'நீங்கள் தகுதியானவர்',
    whyEligible: 'நீங்கள் ஏன் தகுதியானவர்',
    aboutScheme: 'இந்த திட்டத்தைப் பற்றி',
    documentsNeeded: 'தேவையான ஆவணங்கள்',
    howToApply: 'விண்ணப்பிக்கும் முறை',
    applyForScheme: 'இந்த திட்டத்திற்கு விண்ணப்பிக்கவும்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    chatWithUs: 'எங்களுடன் அரட்டையடிக்கவும்',
    askQuestion: 'திட்டங்கள் பற்றி ஒரு கேள்வி கேளுங்கள்...',
    send: 'அனுப்பு',
    chatbotWelcome: 'வணக்கம்! இந்த அரசாங்க திட்டங்களைப் புரிந்து கொள்ள நான் உங்களுக்கு உதவ முடியும். எதையும் கேளுங்கள்!',
  },
  Telugu: {
    yourEligibleSchemes: 'మీ అర్హత ఉన్న పథకాలు',
    found: 'దొరికింది',
    schemes: 'పథకాలు',
    scheme: 'పథకం',
    forYou: 'మీ కోసం',
    logout: 'లాగ్అవుట్',
    yourProfile: 'మీ ప్రొఫైల్',
    age: 'వయస్సు',
    years: 'సంవత్సరాలు',
    gender: 'లింగం',
    occupation: 'వృత్తి',
    state: 'రాష్ట్రం',
    income: 'ఆదాయం',
    noSchemes: 'ప్రస్తుతం మీ ప్రొఫైల్‌కు సరిపోలే పథకాలు లేవు.',
    checkBack: 'దయచేసి తర్వాత మళ్లీ తనిఖీ చేయండి లేదా మీ వివరాలను నవీకరించండి.',
    youAreEligible: 'మీరు అర్హులు',
    whyEligible: 'మీరు ఎందుకు అర్హులు',
    aboutScheme: 'ఈ పథకం గురించి',
    documentsNeeded: 'అవసరమైన పత్రాలు',
    howToApply: 'ఎలా దరఖాస్తు చేయాలి',
    applyForScheme: 'ఈ పథకం కోసం దరఖాస్తు చేయండి',
    selectLanguage: 'భాషను ఎంచుకోండి',
    chatWithUs: 'మాతో చాట్ చేయండి',
    askQuestion: 'పథకాల గురించి ఒక ప్రశ్న అడగండి...',
    send: 'పంపండి',
    chatbotWelcome: 'నమస్కారం! ఈ ప్రభుత్వ పథకాలను అర్థం చేసుకోవడానికి నేను మీకు సహాయం చేయగలను. ఏదైనా అడగండి!',
  },
  Marathi: {
    yourEligibleSchemes: 'तुमच्या पात्र योजना',
    found: 'मिळाल्या',
    schemes: 'योजना',
    scheme: 'योजना',
    forYou: 'तुमच्यासाठी',
    logout: 'लॉग आउट',
    yourProfile: 'तुमची प्रोफाइल',
    age: 'वय',
    years: 'वर्षे',
    gender: 'लिंग',
    occupation: 'व्यवसाय',
    state: 'राज्य',
    income: 'उत्पन्न',
    noSchemes: 'या वेळी तुमच्या प्रोफाइलशी जुळणाऱ्या योजना आढळल्या नाहीत.',
    checkBack: 'कृपया नंतर पुन्हा तपासा किंवा तुमचे तपशील अद्यतनित करा.',
    youAreEligible: 'तुम्ही पात्र आहात',
    whyEligible: 'तुम्ही का पात्र आहात',
    aboutScheme: 'या योजनेबद्दल',
    documentsNeeded: 'आवश्यक कागदपत्रे',
    howToApply: 'अर्ज कसा करावा',
    applyForScheme: 'या योजनेसाठी अर्ज करा',
    selectLanguage: 'भाषा निवडा',
    chatWithUs: 'आमच्याशी चॅट करा',
    askQuestion: 'योजनांबद्दल प्रश्न विचारा...',
    send: 'पाठवा',
    chatbotWelcome: 'नमस्कार! या सरकारी योजना समजून घेण्यासाठी मी तुम्हाला मदत करू शकतो. काहीही विचारा!',
  },
  Bengali: {
    yourEligibleSchemes: 'আপনার যোগ্য প্রকল্প',
    found: 'পাওয়া গেছে',
    schemes: 'প্রকল্প',
    scheme: 'প্রকল্প',
    forYou: 'আপনার জন্য',
    logout: 'লগ আউট',
    yourProfile: 'আপনার প্রোফাইল',
    age: 'বয়স',
    years: 'বছর',
    gender: 'লিঙ্গ',
    occupation: 'পেশা',
    state: 'রাজ্য',
    income: 'আয়',
    noSchemes: 'এই মুহূর্তে আপনার প্রোফাইলের সাথে মিলে এমন কোনও প্রকল্প পাওয়া যায়নি।',
    checkBack: 'অনুগ্রহ করে পরে আবার চেক করুন বা আপনার বিবরণ আপডেট করুন।',
    youAreEligible: 'আপনি যোগ্য',
    whyEligible: 'আপনি কেন যোগ্য',
    aboutScheme: 'এই প্রকল্প সম্পর্কে',
    documentsNeeded: 'প্রয়োজনীয় নথি',
    howToApply: 'কীভাবে আবেদন করবেন',
    applyForScheme: 'এই প্রকল্পের জন্য আবেদন করুন',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    chatWithUs: 'আমাদের সাথে চ্যাট করুন',
    askQuestion: 'প্রকল্প সম্পর্কে একটি প্রশ্ন জিজ্ঞাসা করুন...',
    send: 'পাঠান',
    chatbotWelcome: 'হ্যালো! এই সরকারি প্রকল্পগুলি বুঝতে আমি আপনাকে সাহায্য করতে পারি। যেকোনো কিছু জিজ্ঞাসা করুন!',
  },
  Kannada: {
    yourEligibleSchemes: 'ನಿಮ್ಮ ಅರ್ಹ ಯೋಜನೆಗಳು',
    found: 'ಸಿಕ್ಕಿತು',
    schemes: 'ಯೋಜನೆಗಳು',
    scheme: 'ಯೋಜನೆ',
    forYou: 'ನಿಮಗಾಗಿ',
    logout: 'ಲಾಗ್ ಔಟ್',
    yourProfile: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
    age: 'ವಯಸ್ಸು',
    years: 'ವರ್ಷಗಳು',
    gender: 'ಲಿಂಗ',
    occupation: 'ಉದ್ಯೋಗ',
    state: 'ರಾಜ್ಯ',
    income: 'ಆದಾಯ',
    noSchemes: 'ಈ ಸಮಯದಲ್ಲಿ ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಯಾವುದೇ ಯೋಜನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    checkBack: 'ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೊಮ್ಮೆ ಪರಿಶೀಲಿಸಿ ಅಥವಾ ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ.',
    youAreEligible: 'ನೀವು ಅರ್ಹರು',
    whyEligible: 'ನೀವು ಏಕೆ ಅರ್ಹರು',
    aboutScheme: 'ಈ ಯೋಜನೆ ಬಗ್ಗೆ',
    documentsNeeded: 'ಅಗತ್ಯವಿರುವ ದಾಖಲೆಗಳು',
    howToApply: 'ಹೇಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸುವುದು',
    applyForScheme: 'ಈ ಯೋಜನೆಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    chatWithUs: 'ನಮ್ಮೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ',
    askQuestion: 'ಯೋಜನೆಗಳ ಬಗ್ಗೆ ಪ್ರಶ್ನೆ ಕೇಳಿ...',
    send: 'ಕಳುಹಿಸಿ',
    chatbotWelcome: 'ನಮಸ್ಕಾರ! ಈ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ನಾನು ನಿಮಗೆ ಸಹಾಯ ಮಾಡಬಲ್ಲೆ. ಏನು ಬೇಕಾದರೂ ಕೇಳಿ!',
  },
  Malayalam: {
    yourEligibleSchemes: 'നിങ്ങളുടെ യോഗ്യതയുള്ള പദ്ധതികൾ',
    found: 'കണ്ടെത്തി',
    schemes: 'പദ്ധതികൾ',
    scheme: 'പദ്ധതി',
    forYou: 'നിങ്ങൾക്കായി',
    logout: 'ലോഗൗട്ട്',
    yourProfile: 'നിങ്ങളുടെ പ്രൊഫൈൽ',
    age: 'പ്രായം',
    years: 'വർഷം',
    gender: 'ലിംഗം',
    occupation: 'തൊഴിൽ',
    state: 'സംസ്ഥാനം',
    income: 'വരുമാനം',
    noSchemes: 'ഈ സമയം നിങ്ങളുടെ പ്രൊഫൈലുമായി പൊരുത്തപ്പെടുന്ന പദ്ധതികളൊന്നും കണ്ടെത്തിയില്ല.',
    checkBack: 'ദയവായി പിന്നീട് വീണ്ടും പരിശോധിക്കുക അല്ലെങ്കിൽ നിങ്ങളുടെ വിശദാംശങ്ങൾ അപ്ഡേറ്റ് ചെയ്യുക.',
    youAreEligible: 'നിങ്ങൾ യോഗ്യരാണ്',
    whyEligible: 'എന്തുകൊണ്ട് നിങ്ങൾ യോഗ്യരാണ്',
    aboutScheme: 'ഈ പദ്ധതിയെക്കുറിച്ച്',
    documentsNeeded: 'ആവശ്യമായ രേഖകൾ',
    howToApply: 'എങ്ങനെ അപേക്ഷിക്കാം',
    applyForScheme: 'ഈ പദ്ധതിക്ക് അപേക്ഷിക്കുക',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    chatWithUs: 'ഞങ്ങളോട് ചാറ്റ് ചെയ്യുക',
    askQuestion: 'പദ്ധതികളെക്കുറിച്ച് ഒരു ചോദ്യം ചോദിക്കുക...',
    send: 'അയയ്ക്കുക',
    chatbotWelcome: 'ഹലോ! ഈ സർക്കാർ പദ്ധതികൾ മനസ്സിലാക്കാൻ എനിക്ക് നിങ്ങളെ സഹായിക്കാം. എന്തും ചോദിക്കൂ!',
  },
  Gujarati: {
    yourEligibleSchemes: 'તમારી પાત્ર યોજનાઓ',
    found: 'મળી',
    schemes: 'યોજનાઓ',
    scheme: 'યોજના',
    forYou: 'તમારા માટે',
    logout: 'લૉગ આઉટ',
    yourProfile: 'તમારી પ્રોફાઇલ',
    age: 'ઉંમર',
    years: 'વર્ષ',
    gender: 'લિંગ',
    occupation: 'વ્યવસાય',
    state: 'રાજ્ય',
    income: 'આવક',
    noSchemes: 'આ સમયે તમારી પ્રોફાઇલ સાથે મેળ ખાતી કોઈ યોજનાઓ મળી નથી.',
    checkBack: 'કૃપા કરીને પછીથી ફરી તપાસો અથવા તમારી વિગતો અપડેટ કરો.',
    youAreEligible: 'તમે પાત્ર છો',
    whyEligible: 'તમે શા માટે પાત્ર છો',
    aboutScheme: 'આ યોજના વિશે',
    documentsNeeded: 'જરૂરી દસ્તાવેજો',
    howToApply: 'કેવી રીતે અરજી કરવી',
    applyForScheme: 'આ યોજના માટે અરજી કરો',
    selectLanguage: 'ભાષા પસંદ કરો',
    chatWithUs: 'અમારી સાથે ચેટ કરો',
    askQuestion: 'યોજનાઓ વિશે પ્રશ્ન પૂછો...',
    send: 'મોકલો',
    chatbotWelcome: 'નમસ્તે! આ સરકારી યોજનાઓને સમજવામાં હું તમને મદદ કરી શકું છું. કંઈપણ પૂછો!',
  },
  Punjabi: {
    yourEligibleSchemes: 'ਤੁਹਾਡੀਆਂ ਯੋਗ ਯੋਜਨਾਵਾਂ',
    found: 'ਮਿਲੀਆਂ',
    schemes: 'ਯੋਜਨਾਵਾਂ',
    scheme: 'ਯੋਜਨਾ',
    forYou: 'ਤੁਹਾਡੇ ਲਈ',
    logout: 'ਲਾੱਗ ਆਊਟ',
    yourProfile: 'ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ',
    age: 'ਉਮਰ',
    years: 'ਸਾਲ',
    gender: 'ਲਿੰਗ',
    occupation: 'ਕਿੱਤਾ',
    state: 'ਰਾਜ',
    income: 'ਆਮਦਨ',
    noSchemes: 'ਇਸ ਸਮੇਂ ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਨਾਲ ਮੇਲ ਖਾਂਦੀਆਂ ਕੋਈ ਯੋਜਨਾਵਾਂ ਨਹੀਂ ਮਿਲੀਆਂ।',
    checkBack: 'ਕਿਰਪਾ ਕਰਕੇ ਬਾਅਦ ਵਿੱਚ ਦੁਬਾਰਾ ਜਾਂਚ ਕਰੋ ਜਾਂ ਆਪਣੇ ਵੇਰਵੇ ਅੱਪਡੇਟ ਕਰੋ।',
    youAreEligible: 'ਤੁਸੀਂ ਯੋਗ ਹੋ',
    whyEligible: 'ਤੁਸੀਂ ਕਿਉਂ ਯੋਗ ਹੋ',
    aboutScheme: 'ਇਸ ਯੋਜਨਾ ਬਾਰੇ',
    documentsNeeded: 'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼',
    howToApply: 'ਕਿਵੇਂ ਅਰਜ਼ੀ ਦੇਣੀ ਹੈ',
    applyForScheme: 'ਇਸ ਯੋਜਨਾ ਲਈ ਅਰਜ਼ੀ ਦਿਓ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    chatWithUs: 'ਸਾਡੇ ਨਾਲ ਚੈਟ ਕਰੋ',
    askQuestion: 'ਯੋਜਨਾਵਾਂ ਬਾਰੇ ਸਵਾਲ ਪੁੱਛੋ...',
    send: 'ਭੇਜੋ',
    chatbotWelcome: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਤੁਹਾਨੂੰ ਇਹਨਾਂ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਨੂੰ ਸਮਝਣ ਵਿੱਚ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ। ਕੁਝ ਵੀ ਪੁੱਛੋ!',
  },
  Urdu: {
    yourEligibleSchemes: 'آپ کی اہل اسکیمیں',
    found: 'ملیں',
    schemes: 'اسکیمیں',
    scheme: 'اسکیم',
    forYou: 'آپ کے لیے',
    logout: 'لاگ آؤٹ',
    yourProfile: 'آپ کی پروفائل',
    age: 'عمر',
    years: 'سال',
    gender: 'جنس',
    occupation: 'پیشہ',
    state: 'ریاست',
    income: 'آمدنی',
    noSchemes: 'اس وقت آپ کی پروفائل سے مماثل کوئی اسکیم نہیں ملی۔',
    checkBack: 'براہ کرم بعد میں دوبارہ چیک کریں یا اپنی تفصیلات اپ ڈیٹ کریں۔',
    youAreEligible: 'آپ اہل ہیں',
    whyEligible: 'آپ کیوں اہل ہیں',
    aboutScheme: 'اس اسکیم کے بارے میں',
    documentsNeeded: 'ضروری دستاویزات',
    howToApply: 'کیسے درخواست دیں',
    applyForScheme: 'اس اسکیم کے لیے درخواست دیں',
    selectLanguage: 'زبان منتخب کریں',
    chatWithUs: 'ہم سے بات کریں',
    askQuestion: 'اسکیموں کے بارے میں سوال پوچھیں...',
    send: 'بھیجیں',
    chatbotWelcome: 'السلام علیکم! میں آپ کو ان سرکاری اسکیموں کو سمجھنے میں مدد کر سکتا ہوں۔ کچھ بھی پوچھیں!',
  },
  Odia: {
    yourEligibleSchemes: 'ତୁମର ଯୋଗ୍ୟ ଯୋଜନାଗୁଡ଼ିକ',
    found: 'ମିଳିଲା',
    schemes: 'ଯୋଜନାଗୁଡ଼ିକ',
    scheme: 'ଯୋଜନା',
    forYou: 'ତୁମ ପାଇଁ',
    logout: 'ଲଗ୍ ଆଉଟ୍',
    yourProfile: 'ତୁମର ପ୍ରୋଫାଇଲ୍',
    age: 'ବୟସ',
    years: 'ବର୍ଷ',
    gender: 'ଲିଙ୍ଗ',
    occupation: 'ବୃତ୍ତି',
    state: 'ରାଜ୍ୟ',
    income: 'ଆୟ',
    noSchemes: 'ଏହି ସମୟରେ ତୁମର ପ୍ରୋଫାଇଲ୍ ସହିତ ମେଳ ଖାଉଥିବା କୌଣସି ଯୋଜନା ମିଳିଲା ନାହିଁ।',
    checkBack: 'ଦୟାକରି ପରେ ପୁଣି ଯାଞ୍ଚ କରନ୍ତୁ କିମ୍ବା ଆପଣଙ୍କ ବିବରଣୀ ଅପଡେଟ୍ କରନ୍ତୁ।',
    youAreEligible: 'ତୁମେ ଯୋଗ୍ୟ',
    whyEligible: 'ତୁମେ କାହିଁକି ଯୋଗ୍ୟ',
    aboutScheme: 'ଏହି ଯୋଜନା ବିଷୟରେ',
    documentsNeeded: 'ଆବଶ୍ୟକ ଦଲିଲଗୁଡ଼ିକ',
    howToApply: 'କିପରି ଆବେଦନ କରିବେ',
    applyForScheme: 'ଏହି ଯୋଜନା ପାଇଁ ଆବେଦନ କରନ୍ତୁ',
    selectLanguage: 'ଭାଷା ଚୟନ କରନ୍ତୁ',
    chatWithUs: 'ଆମ ସହିତ ଚାଟ୍ କରନ୍ତୁ',
    askQuestion: 'ଯୋଜନାଗୁଡ଼ିକ ବିଷୟରେ ଏକ ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ...',
    send: 'ପଠାନ୍ତୁ',
    chatbotWelcome: 'ନମସ୍କାର! ମୁଁ ଆପଣଙ୍କୁ ଏହି ସରକାରୀ ଯୋଜନାଗୁଡ଼ିକ ବୁଝିବାରେ ସାହାଯ୍ୟ କରିପାରିବି। କିଛି ବି ପଚାରନ୍ତୁ!',
  },
  Assamese: {
    yourEligibleSchemes: 'আপোনাৰ যোগ্য আঁচনিসমূহ',
    found: 'পোৱা গ\'ল',
    schemes: 'আঁচনিসমূহ',
    scheme: 'আঁচনি',
    forYou: 'আপোনাৰ বাবে',
    logout: 'লগ আউট',
    yourProfile: 'আপোনাৰ প্ৰ\'ফাইল',
    age: 'বয়স',
    years: 'বছৰ',
    gender: 'লিংগ',
    occupation: 'পেছা',
    state: 'ৰাজ্য',
    income: 'আয়',
    noSchemes: 'এই মুহূৰ্তত আপোনাৰ প্ৰ\'ফাইলৰ সৈতে মিল থকা কোনো আঁচনি পোৱা নগ\'ল।',
    checkBack: 'অনুগ্ৰহ কৰি পিছত পুনৰ পৰীক্ষা কৰক বা আপোনাৰ বিৱৰণ আপডেট কৰক।',
    youAreEligible: 'আপুনি যোগ্য',
    whyEligible: 'আপুনি কিয় যোগ্য',
    aboutScheme: 'এই আঁচনিৰ বিষয়ে',
    documentsNeeded: 'প্ৰয়োজনীয় নথি-পত্ৰ',
    howToApply: 'কেনেকৈ আবেদন কৰিব',
    applyForScheme: 'এই আঁচনিৰ বাবে আবেদন কৰক',
    selectLanguage: 'ভাষা নিৰ্বাচন কৰক',
    chatWithUs: 'আমাৰ সৈতে চেট কৰক',
    askQuestion: 'আঁচনিসমূহৰ বিষয়ে প্ৰশ্ন সোধক...',
    send: 'প্ৰেৰণ কৰক',
    chatbotWelcome: 'নমস্কাৰ! এই চৰকাৰী আঁচনিসমূহ বুজিবলৈ মই আপোনাক সহায় কৰিব পাৰোঁ। যিকোনো কথা সোধক!',
  },
  Konkani: {
    yourEligibleSchemes: 'तुमच्या पात्र योजना',
    found: 'मेळ्ळ्यात',
    schemes: 'योजना',
    scheme: 'योजना',
    forYou: 'तुमच्या खातीर',
    logout: 'लॉग आउट',
    yourProfile: 'तुमचो प्रोफाइल',
    age: 'वयस',
    years: 'वर्सां',
    gender: 'लिंग',
    occupation: 'धंदो',
    state: 'राज्य',
    income: 'उत्पन्न',
    noSchemes: 'ह्या वेळार तुमच्या प्रोफाइलाक मेळपी योजना मेळ्ळ्यो ना.',
    checkBack: 'उपकार करून उपरांत परत तपासात वा तुमचे तपशील अद्ययावत करात.',
    youAreEligible: 'तुमी पात्र आसात',
    whyEligible: 'तुमी कित्याक पात्र आसात',
    aboutScheme: 'ह्या योजनेविशीं',
    documentsNeeded: 'गरजेचे कागदपत्र',
    howToApply: 'अर्ज कसो करचो',
    applyForScheme: 'ह्या योजनेखातीर अर्ज करात',
    selectLanguage: 'भास निवडात',
    chatWithUs: 'आमच्याकडेन गप्पा मारात',
    askQuestion: 'योजनांविशीं प्रस्न विचारात...',
    send: 'धाडात',
    chatbotWelcome: 'नमस्कार! ह्या सरकारी योजनांक समजून घेवपाक हांव तुमकां आदार करूं येतां. कितेंय विचारात!',
  },
};
